# Generated by Django 5.1 on 2024-08-31 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_business",
        ),
    ]
