# Generated by Django 5.1 on 2024-08-31 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pricehistory",
            unique_together=set(),
        ),
    ]
