# Generated by Django 5.1 on 2024-08-31 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_alter_pricehistory_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pricehistory",
            unique_together={("stock", "date")},
        ),
    ]
