# Generated by Django 5.1 on 2024-09-01 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0004_stock_expected_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="frequency",
        ),
    ]
